Update 1.20.2 & Gradle 8.3, & Loom updates
MattiDragon/universal-perms pull request #9
Opened 2023-10-03 14:29 UTC by sakura-ryoko

Hey awesome MOD, so I wanted to learn to port stuff, this one was simple enough for me to do.

2023-10-03 14:34 UTC, sakura-ryoko commented
pls forgive the mess, but it should build and install ok... maybe make sure it works with the updated LP 1.20.2 releases.

2023-10-03 18:09 UTC, MattiDragon commented
I'll do a proper review tomorrow, but with a quick look I can see some issues:
- Why dod move/add assets to `bin`? That's not standard for fabric projects
- Why did you change my buildscript (besides the archives base name moving)? I changed from the default dependencies in the example mod for a reason, mine are easier to read for experienced devs.
- Why does the mod icon show as changed?

2023-10-04 11:10 UTC, MattiDragon requested changes

2023-10-04 11:10 UTC, MattiDragon commented on bin/main/fabric.mod.json
Why was this file added? If this is something that your IDE generated then it should be in the gitignore, if you added it yourself then it should be removed

2023-10-04 11:10 UTC, MattiDragon commented on bin/main/universal_perms.mixins.json
Why was this file added? If this is something that your IDE generated then it should be in the gitignore, if you added it yourself then it should be removed

2023-10-04 11:10 UTC, MattiDragon commented on bin/main/universal_perms_icon.png
Why was this file added? If this is something that your IDE generated then it should be in the gitignore, if you added it yourself then it should be removed

2023-10-04 11:10 UTC, MattiDragon commented on bin/main/universal_perms_icon.xcf
Why was this file added? If this is something that your IDE generated then it should be in the gitignore, if you added it yourself then it should be removed

2023-10-04 11:10 UTC, MattiDragon commented on build.gradle
> +        }
Unnessecary and uses the wrong id, please remove

2023-10-04 11:10 UTC, MattiDragon commented on build.gradle
> +        modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
Please don't add back the comments that I deleted from the example mod, same for the unnessecary braces and `project.`.

2023-10-04 11:10 UTC, MattiDragon commented on build.gradle
>  }
Why was this changed?

2023-10-04 11:10 UTC, MattiDragon commented on src/main/java/io/github/mattidragon/universalperms/UniversalPerms.java
> +// UNUSED: import java.util.function.Predicate;
If an import is unused, just remove it. I'd also prefer if you didn't change the imports from the default order intellij puts them in

2023-10-04 11:10 UTC, MattiDragon commented on src/main/java/io/github/mattidragon/universalperms/UniversalPerms.java
> +                });
Please don't unnessecarily reformat my code

2023-10-04 11:10 UTC, MattiDragon commented on src/main/java/io/github/mattidragon/universalperms/UniversalPerms.java
> +            Map<CommandNode<ServerCommandSource>, String> visited) {
Again, please don't reformat for no reason

2023-10-04 11:10 UTC, MattiDragon commented on src/main/java/io/github/mattidragon/universalperms/UniversalPerms.java
> +                    visited.get(node), nodeLocation);
Again, please don't reformat for no reason

2023-10-04 11:10 UTC, MattiDragon commented on src/main/java/io/github/mattidragon/universalperms/UniversalPerms.java
> +                        .orElseGet(() -> requirement.test(source)));
This should probably have been reformatted, but you did it in a way that's really confusing to read

2023-10-04 11:10 UTC, MattiDragon commented on src/main/java/io/github/mattidragon/universalperms/mixin/ServerPlayerEntityMixin.java
> +// FIXME: import net.minecraft.network.encryption.PlayerPublicKey;
Just remove unused imports

2023-10-04 11:10 UTC, MattiDragon commented on src/main/java/io/github/mattidragon/universalperms/mixin/ServerPlayerEntityMixin.java
> +// FIXME: import org.jetbrains.annotations.Nullable;
Just remove unused imports

2023-10-04 11:10 UTC, MattiDragon commented on src/main/java/io/github/mattidragon/universalperms/mixin/ServerPlayerEntityMixin.java
> +    // GameProfile gameProfile, @Nullable PlayerPublicKey publicKey) {
Unnesssary comment. If the method changed, just update the mixin to reflect that, don't leave the old code behind

2023-10-04 11:10 UTC, MattiDragon commented on src/main/resources/fabric.mod.json
> +    "minecraft": "1.20.2",
You removed the `>=` from the versions. This is bad especially for the loader version as any loader version over the one we use should work. This mod is also pretty mc version agnostic so it should also stay on the mc version

2023-10-04 11:11 UTC, MattiDragon commented
I'll probably port this myself once I finish with other mods (which might take a while), but I'll let you try to get your code up to standard and I'll merge this if you fix the issues

2023-10-04 13:58 UTC, sakura-ryoko commented
Its all good, I was just messing with coding for the first time.  You can simply reject the merge if you wish.

2023-10-04 14:05 UTC, closed without merging